name: Publish to Hex.pm

on:
    push:
        tags:
            - "*"

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Setup Erlang
              uses: erlef/setup-beam@v1
              with:
                  otp-version: "27"
                  rebar3-version: "3.25.1"

            - name: Run tests
              run: rebar3 eunit

            - name: Generate documentation
              run: rebar3 edoc

            - name: Publish to Hex.pm
              run: rebar3 hex publish --yes
              env:
                  HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
